type A implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldB: B! @relation(name:"AOnB")
	fieldC: C! @relation(name:"AOnC")
	fieldD: D! @relation(name:"AOnD")
	fieldE: E! @relation(name:"AOnE")
	fieldF: F! @relation(name:"AOnF")
	fieldG: G! @relation(name:"AOnG")
	fieldH: H! @relation(name:"AOnH")
	fieldI: I! @relation(name:"AOnI")
	fieldJ: J! @relation(name:"AOnJ")
	fieldK: K! @relation(name:"AOnK")
	fieldL: L! @relation(name:"AOnL")
	fieldM: M! @relation(name:"AOnM")
	fieldN: N! @relation(name:"AOnN")
	fieldO: O! @relation(name:"AOnO")
	fieldP: P! @relation(name:"AOnP")
	fieldQ: Q! @relation(name:"AOnQ")
	fieldR: R! @relation(name:"AOnR")
	fieldS: S! @relation(name:"AOnS")
	fieldT: T! @relation(name:"AOnT")
}

type B implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnB")
	fieldC: C! @relation(name:"BOnC")
	fieldD: D! @relation(name:"BOnD")
	fieldE: E! @relation(name:"BOnE")
	fieldF: F! @relation(name:"BOnF")
	fieldG: G! @relation(name:"BOnG")
	fieldH: H! @relation(name:"BOnH")
	fieldI: I! @relation(name:"BOnI")
	fieldJ: J! @relation(name:"BOnJ")
	fieldK: K! @relation(name:"BOnK")
	fieldL: L! @relation(name:"BOnL")
	fieldM: M! @relation(name:"BOnM")
	fieldN: N! @relation(name:"BOnN")
	fieldO: O! @relation(name:"BOnO")
	fieldP: P! @relation(name:"BOnP")
	fieldQ: Q! @relation(name:"BOnQ")
	fieldR: R! @relation(name:"BOnR")
	fieldS: S! @relation(name:"BOnS")
	fieldT: T! @relation(name:"BOnT")
}

type C implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnC")
	fieldB: B! @relation(name:"BOnC")
	fieldD: D! @relation(name:"COnD")
	fieldE: E! @relation(name:"COnE")
	fieldF: F! @relation(name:"COnF")
	fieldG: G! @relation(name:"COnG")
	fieldH: H! @relation(name:"COnH")
	fieldI: I! @relation(name:"COnI")
	fieldJ: J! @relation(name:"COnJ")
	fieldK: K! @relation(name:"COnK")
	fieldL: L! @relation(name:"COnL")
	fieldM: M! @relation(name:"COnM")
	fieldN: N! @relation(name:"COnN")
	fieldO: O! @relation(name:"COnO")
	fieldP: P! @relation(name:"COnP")
	fieldQ: Q! @relation(name:"COnQ")
	fieldR: R! @relation(name:"COnR")
	fieldS: S! @relation(name:"COnS")
	fieldT: T! @relation(name:"COnT")
}

type D implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnD")
	fieldB: B! @relation(name:"BOnD")
	fieldC: C! @relation(name:"COnD")
	fieldE: E! @relation(name:"DOnE")
	fieldF: F! @relation(name:"DOnF")
	fieldG: G! @relation(name:"DOnG")
	fieldH: H! @relation(name:"DOnH")
	fieldI: I! @relation(name:"DOnI")
	fieldJ: J! @relation(name:"DOnJ")
	fieldK: K! @relation(name:"DOnK")
	fieldL: L! @relation(name:"DOnL")
	fieldM: M! @relation(name:"DOnM")
	fieldN: N! @relation(name:"DOnN")
	fieldO: O! @relation(name:"DOnO")
	fieldP: P! @relation(name:"DOnP")
	fieldQ: Q! @relation(name:"DOnQ")
	fieldR: R! @relation(name:"DOnR")
	fieldS: S! @relation(name:"DOnS")
	fieldT: T! @relation(name:"DOnT")
}

type E implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnE")
	fieldB: B! @relation(name:"BOnE")
	fieldC: C! @relation(name:"COnE")
	fieldD: D! @relation(name:"DOnE")
	fieldF: F! @relation(name:"EOnF")
	fieldG: G! @relation(name:"EOnG")
	fieldH: H! @relation(name:"EOnH")
	fieldI: I! @relation(name:"EOnI")
	fieldJ: J! @relation(name:"EOnJ")
	fieldK: K! @relation(name:"EOnK")
	fieldL: L! @relation(name:"EOnL")
	fieldM: M! @relation(name:"EOnM")
	fieldN: N! @relation(name:"EOnN")
	fieldO: O! @relation(name:"EOnO")
	fieldP: P! @relation(name:"EOnP")
	fieldQ: Q! @relation(name:"EOnQ")
	fieldR: R! @relation(name:"EOnR")
	fieldS: S! @relation(name:"EOnS")
	fieldT: T! @relation(name:"EOnT")
}

type F implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnF")
	fieldB: B! @relation(name:"BOnF")
	fieldC: C! @relation(name:"COnF")
	fieldD: D! @relation(name:"DOnF")
	fieldE: E! @relation(name:"EOnF")
	fieldG: G! @relation(name:"FOnG")
	fieldH: H! @relation(name:"FOnH")
	fieldI: I! @relation(name:"FOnI")
	fieldJ: J! @relation(name:"FOnJ")
	fieldK: K! @relation(name:"FOnK")
	fieldL: L! @relation(name:"FOnL")
	fieldM: M! @relation(name:"FOnM")
	fieldN: N! @relation(name:"FOnN")
	fieldO: O! @relation(name:"FOnO")
	fieldP: P! @relation(name:"FOnP")
	fieldQ: Q! @relation(name:"FOnQ")
	fieldR: R! @relation(name:"FOnR")
	fieldS: S! @relation(name:"FOnS")
	fieldT: T! @relation(name:"FOnT")
}

type G implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnG")
	fieldB: B! @relation(name:"BOnG")
	fieldC: C! @relation(name:"COnG")
	fieldD: D! @relation(name:"DOnG")
	fieldE: E! @relation(name:"EOnG")
	fieldF: F! @relation(name:"FOnG")
	fieldH: H! @relation(name:"GOnH")
	fieldI: I! @relation(name:"GOnI")
	fieldJ: J! @relation(name:"GOnJ")
	fieldK: K! @relation(name:"GOnK")
	fieldL: L! @relation(name:"GOnL")
	fieldM: M! @relation(name:"GOnM")
	fieldN: N! @relation(name:"GOnN")
	fieldO: O! @relation(name:"GOnO")
	fieldP: P! @relation(name:"GOnP")
	fieldQ: Q! @relation(name:"GOnQ")
	fieldR: R! @relation(name:"GOnR")
	fieldS: S! @relation(name:"GOnS")
	fieldT: T! @relation(name:"GOnT")
}

type H implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnH")
	fieldB: B! @relation(name:"BOnH")
	fieldC: C! @relation(name:"COnH")
	fieldD: D! @relation(name:"DOnH")
	fieldE: E! @relation(name:"EOnH")
	fieldF: F! @relation(name:"FOnH")
	fieldG: G! @relation(name:"GOnH")
	fieldI: I! @relation(name:"HOnI")
	fieldJ: J! @relation(name:"HOnJ")
	fieldK: K! @relation(name:"HOnK")
	fieldL: L! @relation(name:"HOnL")
	fieldM: M! @relation(name:"HOnM")
	fieldN: N! @relation(name:"HOnN")
	fieldO: O! @relation(name:"HOnO")
	fieldP: P! @relation(name:"HOnP")
	fieldQ: Q! @relation(name:"HOnQ")
	fieldR: R! @relation(name:"HOnR")
	fieldS: S! @relation(name:"HOnS")
	fieldT: T! @relation(name:"HOnT")
}

type I implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnI")
	fieldB: B! @relation(name:"BOnI")
	fieldC: C! @relation(name:"COnI")
	fieldD: D! @relation(name:"DOnI")
	fieldE: E! @relation(name:"EOnI")
	fieldF: F! @relation(name:"FOnI")
	fieldG: G! @relation(name:"GOnI")
	fieldH: H! @relation(name:"HOnI")
	fieldJ: J! @relation(name:"IOnJ")
	fieldK: K! @relation(name:"IOnK")
	fieldL: L! @relation(name:"IOnL")
	fieldM: M! @relation(name:"IOnM")
	fieldN: N! @relation(name:"IOnN")
	fieldO: O! @relation(name:"IOnO")
	fieldP: P! @relation(name:"IOnP")
	fieldQ: Q! @relation(name:"IOnQ")
	fieldR: R! @relation(name:"IOnR")
	fieldS: S! @relation(name:"IOnS")
	fieldT: T! @relation(name:"IOnT")
}

type J implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnJ")
	fieldB: B! @relation(name:"BOnJ")
	fieldC: C! @relation(name:"COnJ")
	fieldD: D! @relation(name:"DOnJ")
	fieldE: E! @relation(name:"EOnJ")
	fieldF: F! @relation(name:"FOnJ")
	fieldG: G! @relation(name:"GOnJ")
	fieldH: H! @relation(name:"HOnJ")
	fieldI: I! @relation(name:"IOnJ")
	fieldK: K! @relation(name:"JOnK")
	fieldL: L! @relation(name:"JOnL")
	fieldM: M! @relation(name:"JOnM")
	fieldN: N! @relation(name:"JOnN")
	fieldO: O! @relation(name:"JOnO")
	fieldP: P! @relation(name:"JOnP")
	fieldQ: Q! @relation(name:"JOnQ")
	fieldR: R! @relation(name:"JOnR")
	fieldS: S! @relation(name:"JOnS")
	fieldT: T! @relation(name:"JOnT")
}

type K implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnK")
	fieldB: B! @relation(name:"BOnK")
	fieldC: C! @relation(name:"COnK")
	fieldD: D! @relation(name:"DOnK")
	fieldE: E! @relation(name:"EOnK")
	fieldF: F! @relation(name:"FOnK")
	fieldG: G! @relation(name:"GOnK")
	fieldH: H! @relation(name:"HOnK")
	fieldI: I! @relation(name:"IOnK")
	fieldJ: J! @relation(name:"JOnK")
	fieldL: L! @relation(name:"KOnL")
	fieldM: M! @relation(name:"KOnM")
	fieldN: N! @relation(name:"KOnN")
	fieldO: O! @relation(name:"KOnO")
	fieldP: P! @relation(name:"KOnP")
	fieldQ: Q! @relation(name:"KOnQ")
	fieldR: R! @relation(name:"KOnR")
	fieldS: S! @relation(name:"KOnS")
	fieldT: T! @relation(name:"KOnT")
}

type L implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnL")
	fieldB: B! @relation(name:"BOnL")
	fieldC: C! @relation(name:"COnL")
	fieldD: D! @relation(name:"DOnL")
	fieldE: E! @relation(name:"EOnL")
	fieldF: F! @relation(name:"FOnL")
	fieldG: G! @relation(name:"GOnL")
	fieldH: H! @relation(name:"HOnL")
	fieldI: I! @relation(name:"IOnL")
	fieldJ: J! @relation(name:"JOnL")
	fieldK: K! @relation(name:"KOnL")
	fieldM: M! @relation(name:"LOnM")
	fieldN: N! @relation(name:"LOnN")
	fieldO: O! @relation(name:"LOnO")
	fieldP: P! @relation(name:"LOnP")
	fieldQ: Q! @relation(name:"LOnQ")
	fieldR: R! @relation(name:"LOnR")
	fieldS: S! @relation(name:"LOnS")
	fieldT: T! @relation(name:"LOnT")
}

type M implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnM")
	fieldB: B! @relation(name:"BOnM")
	fieldC: C! @relation(name:"COnM")
	fieldD: D! @relation(name:"DOnM")
	fieldE: E! @relation(name:"EOnM")
	fieldF: F! @relation(name:"FOnM")
	fieldG: G! @relation(name:"GOnM")
	fieldH: H! @relation(name:"HOnM")
	fieldI: I! @relation(name:"IOnM")
	fieldJ: J! @relation(name:"JOnM")
	fieldK: K! @relation(name:"KOnM")
	fieldL: L! @relation(name:"LOnM")
	fieldN: N! @relation(name:"MOnN")
	fieldO: O! @relation(name:"MOnO")
	fieldP: P! @relation(name:"MOnP")
	fieldQ: Q! @relation(name:"MOnQ")
	fieldR: R! @relation(name:"MOnR")
	fieldS: S! @relation(name:"MOnS")
	fieldT: T! @relation(name:"MOnT")
}

type N implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnN")
	fieldB: B! @relation(name:"BOnN")
	fieldC: C! @relation(name:"COnN")
	fieldD: D! @relation(name:"DOnN")
	fieldE: E! @relation(name:"EOnN")
	fieldF: F! @relation(name:"FOnN")
	fieldG: G! @relation(name:"GOnN")
	fieldH: H! @relation(name:"HOnN")
	fieldI: I! @relation(name:"IOnN")
	fieldJ: J! @relation(name:"JOnN")
	fieldK: K! @relation(name:"KOnN")
	fieldL: L! @relation(name:"LOnN")
	fieldM: M! @relation(name:"MOnN")
	fieldO: O! @relation(name:"NOnO")
	fieldP: P! @relation(name:"NOnP")
	fieldQ: Q! @relation(name:"NOnQ")
	fieldR: R! @relation(name:"NOnR")
	fieldS: S! @relation(name:"NOnS")
	fieldT: T! @relation(name:"NOnT")
}

type O implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnO")
	fieldB: B! @relation(name:"BOnO")
	fieldC: C! @relation(name:"COnO")
	fieldD: D! @relation(name:"DOnO")
	fieldE: E! @relation(name:"EOnO")
	fieldF: F! @relation(name:"FOnO")
	fieldG: G! @relation(name:"GOnO")
	fieldH: H! @relation(name:"HOnO")
	fieldI: I! @relation(name:"IOnO")
	fieldJ: J! @relation(name:"JOnO")
	fieldK: K! @relation(name:"KOnO")
	fieldL: L! @relation(name:"LOnO")
	fieldM: M! @relation(name:"MOnO")
	fieldN: N! @relation(name:"NOnO")
	fieldP: P! @relation(name:"OOnP")
	fieldQ: Q! @relation(name:"OOnQ")
	fieldR: R! @relation(name:"OOnR")
	fieldS: S! @relation(name:"OOnS")
	fieldT: T! @relation(name:"OOnT")
}

type P implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnP")
	fieldB: B! @relation(name:"BOnP")
	fieldC: C! @relation(name:"COnP")
	fieldD: D! @relation(name:"DOnP")
	fieldE: E! @relation(name:"EOnP")
	fieldF: F! @relation(name:"FOnP")
	fieldG: G! @relation(name:"GOnP")
	fieldH: H! @relation(name:"HOnP")
	fieldI: I! @relation(name:"IOnP")
	fieldJ: J! @relation(name:"JOnP")
	fieldK: K! @relation(name:"KOnP")
	fieldL: L! @relation(name:"LOnP")
	fieldM: M! @relation(name:"MOnP")
	fieldN: N! @relation(name:"NOnP")
	fieldO: O! @relation(name:"OOnP")
	fieldQ: Q! @relation(name:"POnQ")
	fieldR: R! @relation(name:"POnR")
	fieldS: S! @relation(name:"POnS")
	fieldT: T! @relation(name:"POnT")
}

type Q implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnQ")
	fieldB: B! @relation(name:"BOnQ")
	fieldC: C! @relation(name:"COnQ")
	fieldD: D! @relation(name:"DOnQ")
	fieldE: E! @relation(name:"EOnQ")
	fieldF: F! @relation(name:"FOnQ")
	fieldG: G! @relation(name:"GOnQ")
	fieldH: H! @relation(name:"HOnQ")
	fieldI: I! @relation(name:"IOnQ")
	fieldJ: J! @relation(name:"JOnQ")
	fieldK: K! @relation(name:"KOnQ")
	fieldL: L! @relation(name:"LOnQ")
	fieldM: M! @relation(name:"MOnQ")
	fieldN: N! @relation(name:"NOnQ")
	fieldO: O! @relation(name:"OOnQ")
	fieldP: P! @relation(name:"POnQ")
	fieldR: R! @relation(name:"QOnR")
	fieldS: S! @relation(name:"QOnS")
	fieldT: T! @relation(name:"QOnT")
}

type R implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnR")
	fieldB: B! @relation(name:"BOnR")
	fieldC: C! @relation(name:"COnR")
	fieldD: D! @relation(name:"DOnR")
	fieldE: E! @relation(name:"EOnR")
	fieldF: F! @relation(name:"FOnR")
	fieldG: G! @relation(name:"GOnR")
	fieldH: H! @relation(name:"HOnR")
	fieldI: I! @relation(name:"IOnR")
	fieldJ: J! @relation(name:"JOnR")
	fieldK: K! @relation(name:"KOnR")
	fieldL: L! @relation(name:"LOnR")
	fieldM: M! @relation(name:"MOnR")
	fieldN: N! @relation(name:"NOnR")
	fieldO: O! @relation(name:"OOnR")
	fieldP: P! @relation(name:"POnR")
	fieldQ: Q! @relation(name:"QOnR")
	fieldS: S! @relation(name:"ROnS")
	fieldT: T! @relation(name:"ROnT")
}

type S implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnS")
	fieldB: B! @relation(name:"BOnS")
	fieldC: C! @relation(name:"COnS")
	fieldD: D! @relation(name:"DOnS")
	fieldE: E! @relation(name:"EOnS")
	fieldF: F! @relation(name:"FOnS")
	fieldG: G! @relation(name:"GOnS")
	fieldH: H! @relation(name:"HOnS")
	fieldI: I! @relation(name:"IOnS")
	fieldJ: J! @relation(name:"JOnS")
	fieldK: K! @relation(name:"KOnS")
	fieldL: L! @relation(name:"LOnS")
	fieldM: M! @relation(name:"MOnS")
	fieldN: N! @relation(name:"NOnS")
	fieldO: O! @relation(name:"OOnS")
	fieldP: P! @relation(name:"POnS")
	fieldQ: Q! @relation(name:"QOnS")
	fieldR: R! @relation(name:"ROnS")
	fieldT: T! @relation(name:"SOnT")
}

type T implements Node {
    id: ID! @isUnique
    field1: String!
    field2: String
    field3: [Int]
    fieldA: A! @relation(name:"AOnT")
	fieldB: B! @relation(name:"BOnT")
	fieldC: C! @relation(name:"COnT")
	fieldD: D! @relation(name:"DOnT")
	fieldE: E! @relation(name:"EOnT")
	fieldF: F! @relation(name:"FOnT")
	fieldG: G! @relation(name:"GOnT")
	fieldH: H! @relation(name:"HOnT")
	fieldI: I! @relation(name:"IOnT")
	fieldJ: J! @relation(name:"JOnT")
	fieldK: K! @relation(name:"KOnT")
	fieldL: L! @relation(name:"LOnT")
	fieldM: M! @relation(name:"MOnT")
	fieldN: N! @relation(name:"NOnT")
	fieldO: O! @relation(name:"OOnT")
	fieldP: P! @relation(name:"POnT")
	fieldQ: Q! @relation(name:"QOnT")
	fieldR: R! @relation(name:"ROnT")
	fieldS: S! @relation(name:"SOnT")
}

