ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/airbnb > __tests__/blackbox/cases/airbnb/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/financial > __tests__/blackbox/cases/financial/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/relationNames > __tests__/blackbox/cases/relationNames/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/selfReferencing > __tests__/blackbox/cases/selfReferencing/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/twoSidedConnection > __tests__/blackbox/cases/twoSidedConnection/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/defaultValue > __tests__/blackbox/cases/defaultValue/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/meshRelation > __tests__/blackbox/cases/meshRelation/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/relations > __tests__/blackbox/cases/relations/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/simple > __tests__/blackbox/cases/simple/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/withAndWithoutId > __tests__/blackbox/cases/withAndWithoutId/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/enum > __tests__/blackbox/cases/enum/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/oneSidedConnection > __tests__/blackbox/cases/oneSidedConnection/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/scalars > __tests__/blackbox/cases/scalars/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/todo  > __tests__/blackbox/cases/todo/prisma.graphql
ts-node scripts/fetchSchemaFromEndpoint.ts http://localhost:4466/schema-generator/prisma-3143 > __tests__/blackbox/cases/prisma-3143/prisma.graphql
