package com.prisma.deploy.connector.jdbc.database

import com.prisma.gc_values.GCValue
import com.prisma.shared.models.Field
import com.prisma.shared.models.TypeIdentifier.TypeIdentifier
import org.jooq.impl.DSL.name

trait TypeMapper {
  def rawSQLForField(field: Field): String
  def rawSQLFromParts(
      name: String,
      isRequired: Boolean,
      isList: Boolean,
      typeIdentifier: TypeIdentifier,
      isAutoGenerated: Boolean = false,
      defaultValue: Option[GCValue] = None
  ): String

  def rawSqlTypeForScalarTypeIdentifier(isList: Boolean, t: TypeIdentifier): String

  def esc(n: String): String = name(n).toString
}
