const { version } = require('../../package.json')

export const codeComment = `// Code generated by Prisma (prisma@${version}). DO NOT EDIT.
  // Please don't change this file manually but run \`prisma generate\` to update it.
  // For more information, please read the docs: https://www.prisma.io/docs/prisma-client/`
