package com.prisma.deploy.connector.mongo.impl

import com.prisma.deploy.connector.{FieldRequirement, FieldRequirementsInterface}
import com.prisma.shared.models.FieldTemplate

case class MongoFieldRequirement(
    isActive: Boolean
) extends FieldRequirementsInterface {
  val idFieldRequirement = Vector(FieldRequirement("id", Vector("ID"), required = true, unique = true, list = false))

  val baseReservedFieldsRequirements = Vector(
    FieldRequirement("updatedAt", "DateTime", required = true, unique = false, list = false),
    FieldRequirement("createdAt", "DateTime", required = true, unique = false, list = false)
  )

  val reservedFieldRequirements: Vector[FieldRequirement] = baseReservedFieldsRequirements ++ idFieldRequirement
  val requiredReservedFields: Vector[FieldRequirement]    = Vector.empty
  val hiddenReservedField: Vector[FieldTemplate]          = Vector.empty
  val isAutogenerated: Boolean                            = true
}
