package com.prisma.api.connector.jdbc.database

import com.prisma.api.connector.{Filter, PrismaArgs}
import com.prisma.gc_values._
import com.prisma.shared.models.TypeIdentifier.IdTypeIdentifier
import com.prisma.shared.models.{Model, TypeIdentifier}
import slick.dbio.DBIOAction

import scala.concurrent.ExecutionContext

trait NodeActions extends BuilderBase with FilterConditionBuilder with ScalarListActions with RelayIdActions {
  import slickDatabase.profile.api._

  def createNode(model: Model, args: PrismaArgs): DBIO[IdGCValue] = {
    val idIsAutoGenerated = model.idField_!.isAutoGenerated
    val argsAsRoot = if (idIsAutoGenerated) {
      args.raw.asRoot
    } else {
      args.raw.asRoot.add(model.idField_!.name, generateId(model))
    }

    val fields = model.fields.filter(field => argsAsRoot.hasArgFor(field.name))
    val query = sql
      .insertInto(modelTable(model))
      .columns(fields.map(modelColumn): _*)
      .values(placeHolders(fields))

    insertReturningGeneratedKeysToDBIO(query)(
      setParams = { pp =>
        fields.foreach { field =>
          pp.setGcValue(argsAsRoot.map(field.name))
        }
      },
      readResult = { rs =>
        if (idIsAutoGenerated) {
          rs.next()
          rs.getId(model)
        } else {
          argsAsRoot.idField
        }
      }
    )
  }

  private def generateId(model: Model) = {
    model.idField_!.typeIdentifier.asInstanceOf[IdTypeIdentifier] match {
      case TypeIdentifier.UUID => UuidGCValue.random
      case TypeIdentifier.Cuid => CuidGCValue.random
      case TypeIdentifier.Int  => sys.error("can't generate int ids")
    }
  }

  def updateNodeById(model: Model, id: IdGCValue, updateArgs: PrismaArgs): DBIO[_] = {
    if (updateArgs.raw.asRoot.map.isEmpty) {
      DBIOAction.successful(id)
    } else {
      val actualArgs = updateArgs.raw.asRoot
      val columns    = actualArgs.map.map { case (k, _) => model.getFieldByName_!(k).dbName }.toList
      val values     = actualArgs.map.map { case (_, v) => v }

      val query = sql
        .update(modelTable(model))
        .setColumnsWithPlaceHolders(columns)
        .where(idField(model).equal(placeHolder))

      updateToDBIO(query)(
        setParams = { pp =>
          values.foreach(pp.setGcValue)
          pp.setGcValue(id)
        }
      )
    }
  }

  def updateNodes(model: Model, args: PrismaArgs, whereFilter: Option[Filter]): DBIO[_] = {
    if (args.raw.asRoot.map.nonEmpty) {
      val aliasedTable = modelTable(model).as(topLevelAlias)
      val condition    = buildConditionForFilter(whereFilter)

      val columns = args.raw.asRoot.map.map { case (k, _) => model.getFieldByName_!(k).dbName }.toList
      val query = sql
        .update(aliasedTable)
        .setColumnsWithPlaceHolders(columns)
        .where(condition)

      updateToDBIO(query)(
        setParams = pp => {
          args.raw.asRoot.map.foreach { case (_, v) => pp.setGcValue(v) }
          whereFilter.foreach(filter => SetParams.setFilter(pp, filter))
        }
      )
    } else {
      dbioUnit
    }
  }

  def deleteNodeById(model: Model, id: IdGCValue, shouldDeleteRelayIds: Boolean)(implicit ec: ExecutionContext) = {
    deleteNodes(model, Vector(id), shouldDeleteRelayIds)
  }

  def deleteNodes(model: Model, ids: Vector[IdGCValue], shouldDeleteRelayIds: Boolean)(implicit ec: ExecutionContext): DBIO[Unit] = {
    DBIO.seq(
      deleteScalarListValuesByNodeIds(model, ids),
      if (shouldDeleteRelayIds) deleteRelayIds(ids) else dbioUnit,
      deleteNodesByIds(model, ids)
    )
  }

  private def deleteNodesByIds(model: Model, ids: Vector[IdGCValue]): DBIO[Unit] = {
    val query = sql
      .deleteFrom(modelTable(model))
      .where(idField(model).in(placeHolders(ids)))

    deleteToDBIO(query)(
      setParams = pp => ids.foreach(pp.setGcValue)
    )
  }

  private val dbioUnit = DBIO.successful(())
}
